// Generated by Wrangler on Sat Jul 13 2024 01:45:18 GMT+0900 (日本標準時)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	WEBSITE_DOMAIN: "cf-next-blog-example.pages.dev";
	AUTH_GOOGLE_ID: string;
	AUTH_GOOGLE_SECRET: string;
	AUTH_SECRET: string;
	DB: D1Database;
}
