import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { auth } from "@/auth";
import { SignInButton } from "./signin-button";
import { AccountMenu } from "./account-menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = async ({
  children,
}) => {
  const session = await auth();

  return (
    <html lang="ja">
      <body className={`${inter.className} text-neutral-800`}>
        <Providers session={session}>
          <div className="fixed right-4 top-4 w-fit">
            {session ? <AccountMenu session={session} /> : <SignInButton />}
          </div>
          <div className="px-4 py-24">{children}</div>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;

export const runtime = "edge";
